# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
- script: |
     sudo apt update
     sudo apt install -y ansible

- script: |
    terraform init
  displayName: 'Initialize Terrform Project'

- script: |
    terraform apply --auto-approve
  displayName: 'Provision 3 VMs and Install Nginx Web Server'
